export const columns = [
  { field: "Sl_No", headerName: "Sl_No", width: 90 },
  {
    field: "Business_code",
    headerName: " Business_code",
    width: 150,
    editable: true,
  },
  {
    field: "Cust_number",
    headerName: "Cust_number",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Clear_date",
    headerName: "Clear_date",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Buisness_year",
    headerName: "Buisness_year",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Doc_id",
    headerName: "Doc_id",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Posting_date",
    headerName: "Posting_date",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Document_create_date",
    headerName: "Document_create_date",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Document_create_date1",
    headerName: "Document_create_date1",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Due_in_date",
    headerName: "Due_in_date",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Invoice_currency",
    headerName: "Invoice_currency",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Document_type",
    headerName: "Document_type",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Posting_id",
    headerName: "Posting_id",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Area_business",
    headerName: "Area_business",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Total_open_amount",
    headerName: "Total_open_amount",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Baseline_create_date",
    headerName: "Baseline_create_date",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Cust_payment_terms",
    headerName: "Cust_payment_terms",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Invoice_id",
    headerName: "Invoice_id",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "IsOpen",
    headerName: "IsOpen",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Aging_Bucket",
    headerName: "Aging_Bucket",
    type: "number",
    width: 110,
    editable: true,
  },
  {
    field: "Is_deleted",
    headerName: "Is_deleted",
    type: "number",
    width: 110,
    editable: true,
  },
];
